### ISSUE TITLE
peer review from ricken (Group 51)

### ISSUE THREAD

**Issue by Rickenn** [Kylie309/2024-US-election-prediction#5]
Summary:
This repo use data from the General Election of the United States in 2024. This is for prediction the winner of Election, but this repo still not finished, is just a beginning.

Strong positive points:
Good structure with the start folder that professor provided.
No evidence shows that it is associated with STA304.
Brief commits to summary the every update.

Critical improvements needed:
Many files that not be use are still in your repo, you should delete them.
The model doesn't have enough explain or instruction.
Please check the citation for package and document.
Have commits but the commits not clear enough, it cant summary what you update.
If you use some AI tools please updated the LLM document and write in readme text.

Suggestions for improvement:
Explain what methods you used in this repo.
Describe the model to let audience understand.
Explain the model and the result more detailed.
Have more subhead to make each topic clear.
Write commits more clear to show what you update.
Cite correctly.
Remove the useless document.

Evaluation:

R is appropriately cited (1 pts):
1/1: Has R referenced

Data are appropriately cited (1 pts):
0/1: Only has R citation.

Class paper (1 pts):
1/1: No indication this is about sta304.

LLM usage documented (1 pts):
0/1: Dont explain the AI in LLM.

Title (2 pts):
1/2: The title could be more descriptive.

Author, date, and repo (2 pts):
2/2: Has author name, date, and GitHub repo link.

Abstract (4 pts):
2/4: The abstract don't explain the importance of this repo.

Introduction (4 pts):
0/4: No introduction

Estimand (1 pts):
0/1: No estimand

Data (10 pts):
0/10: No summary for clean data.

Measurement (4 pts):
0/4: No Measurement

Model (10 pts):
0/10: Have no idea about this model.

Results (10 pts):
0/10: No Results.

Discussion (10 pts):
0/10: Not Discussion.

Prose (6 pts):
1/6: Check the typo, size, it should be time in new romance, 12, double space.

Cross-references (1 pts):
0/1: No Cross-references.

Captions (2 pts):
0/2: No Captions.

Graphs/tables/etc (4 pts):
0/4: No Graphs

Idealized methodology (10 pts):
0/10: No idealized methodology.

Idealized survey (4 pts):
0/4: No Idealized survey.

Pollster methodology overview and evaluation (10 pts):
0/10: Not Pollster methodology overview and evaluation.

Referencing (4 pts):
1/4: Reference the R but not others.

Commits (2 pts):
1/2: Commits not clear.

Sketches (2 pts):
0/2: No Sketches.

Simulation (4 pts):
0/4: No Simulation.

Tests - simulation (4 pts):
0/4: No Tests.

Tests - actual (4 pts):
0/4: No Tests.

Parquet (1 pts):
0.5/1: Only mentioned the raw data.

Reproducible workflow (4 pts):
1/4: No set.seed can't make sure reproducible.

Miscellaneous (3 pts):
0/3: Unfinished

Estimated overall mark:
11.5/126.

Other Comments

This is a unfinished repo, but it already has a good start and nice frame work. However, this repo only has a structure without content. The author need to enrich the content about model, explanation, describtion to get a good grade.

**Comment by Kylie309** [comment]
Thank you very much for your comment! We have deleted the unecessary files, described and explained the models, made appropriate citations and included more context in the paper.
