### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [Kylie309/2024-US-election-prediction#7]
- R is appropriately cited (1/1)
	- Great.
- Data are appropriately cited (1/1)
	- Great.
- Class paper (1/1)
	- Great
- LLM usage is documented (1/1)
	- Great.
- Title (-/2)
	- Subtitle needs to be move specific about major finding.
- Author, date, and repo (2/2)
	- Great.
- Abstract (1/4)
	- What is found? Please review what goes into an abstract.
- Introduction (0/4)
	- Not done.
- Estimand (0/1)
	- Not done.
- Data (0/10)
	- Not done.
- Measurement (0/4)
	- Not done.
- Model (7/10)
	- Fine.
- Results (6/10)
	- Okay
- Discussion (6/10)
	- Okay
- Prose (3/6)
	- Try to be more concise.
- Cross-references (1/1)
	- Great
- Captions (0/2)
	- Captions are limited.
- Graphs/tables/etc (-/4)
	- Figure 2 is too cramped. You don't need the legend because the facet label is the same.
- Idealized methodology (5/10)
	- I need you to define these terms to show me that you understand them. You should also link to outside literature etc. This is a really important section.
- Idealized survey (3/4)
	- Could be more sophisticated.
- Pollster methodology overview and evaluation (5/10)
	- Please see comments for "Idealized methodology"
- Referencing (0/4)
	- "Post, New York" is wrong. Please fix with double braces.
- Commits (2/2)
	- Great.
- Sketches (0/2)
	- Not done
- Simulation (0/4)
	- Not done
- Tests-simulation (0/4)
	- Not done
- Tests-actual (0/4)
	- Not done
- Parquet (1/1)
	- Great.
- Reproducible workflow (0/4)
	- Don't forget to comment on and close all Issues as you address them.
- Miscellaneous (0/3)
	- None.

**Comment by Kylie309** [comment]
Thank you so much for your time Rohan! We have refined our paper to a better version according to your guidelines. We have completed data simulation and testing, sketches, added estimand, data, introduction and abstract sections in the paper. We have also lots of sections to make the paper more complete. We appreciate your quick, meaningful comments on our paper, and they really help a lot!
